services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - DB_URL=${DB_URL}
      - ORIGIN=${ORIGIN}
      - UPLOAD_LOCATION=${UPLOAD_LOCATION}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: