name: Terraform Apply

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: ${{ vars.ACTIVE_ENVIRONMENT }}

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2
          role-duration-seconds: 14400

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.4

      - name: Create terraform.tfvars
        run: |
          cat <<'EOF' > terraform.tfvars
          ${{ secrets.TF_VARS }}
          EOF

      - name: Terraform Init
        run: terraform init -backend-config="key=${{ vars.ACTIVE_ENVIRONMENT }}/terraform.tfstate"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -var-file=terraform.tfvars